{% set version = "2.41" %}

package:
    name: libuuid
    version: {{ version }}

source:
    # use github mirror to make it easier for bot to scrape for new versions
    url: https://github.com/util-linux/util-linux/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 277407acf21815006eb4bb2ee9c2fa2ea6f4f84bfc57486c460c6bc8c77a4445
    patches:
      - darwin_libtoolize.patch
      # Likely already fixed in the version after 2.41
      # https://github.com/util-linux/util-linux/commit/bbfbd64e3f00c548016c8b8292ff0cb841e681f0
      - fix-uuid_time_on_macos_without_attribute_alias.patch

build:
    number: 0
    skip: True  # [win]
    run_exports:
        # https://abi-laboratory.pro/index.php?view=timeline&l=util-linux
        - {{ pin_subpackage('libuuid') }}

requirements:
    build:
        - autoconf  # [unix]
        - automake  # [unix]
        - bison     # [unix]
        - flex      # [unix]
        - gettext-tools  # [unix]
        - libiconv  # [unix]
        - libtool   # [unix]
        - gnuconfig  # [unix]
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - make  # [unix]

test:
    commands:
        - test -f ${PREFIX}/lib/libuuid.a  # [not win]
        - test -f ${PREFIX}/lib/libuuid${SHLIB_EXT}  # [not win]

about:
    home: http://sourceforge.net/projects/libuuid/
    license: BSD-3-Clause
    license_file: COPYING
    summary: 'Portable uuid C library.'

extra:
    recipe-maintainers:
        - ocefpaf
