{% set version = "2.41.2" %}

package:
  name: libuuid
  version: {{ version }}

source:
    # use github mirror to make it easier for bot to scrape for new versions
  url: https://github.com/util-linux/util-linux/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 534aa113a323d6866c5f46baf909618dcc60c391ad24a91814e5d21511cefd30
  patches:
    - darwin_libtoolize.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
        # https://abi-laboratory.pro/index.php?view=timeline&l=util-linux
    - {{ pin_subpackage('libuuid') }}

requirements:
  build:
    - autoconf      # [unix]
    - automake      # [unix]
    - bison         # [unix]
    - flex          # [unix]
    - gettext-tools      # [unix]
    - libiconv      # [unix]
    - libtool       # [unix]
    - gnuconfig      # [unix]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - make      # [unix]

test:
  commands:
    - test -f ${PREFIX}/lib/libuuid.a      # [not win]
    - test -f ${PREFIX}/lib/libuuid${SHLIB_EXT}      # [not win]

about:
  home: http://sourceforge.net/projects/libuuid/
  license: BSD-3-Clause
  license_file: COPYING
  summary: 'Portable uuid C library.'

extra:
  recipe-maintainers:
    - hmaarrfk
    - ocefpaf
