schema_version: 1

context:
  version: 2.41.2

package:
  name: libuuid
  version: ${{ version }}

source:
  # use github mirror to make it easier for bot to scrape for new versions
  url: https://github.com/util-linux/util-linux/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 534aa113a323d6866c5f46baf909618dcc60c391ad24a91814e5d21511cefd30
  patches:
    - darwin_libtoolize.patch

build:
  number: 1
  skip: win

requirements:
  build:
    - if: unix
      then: autoconf
    - if: unix
      then: automake
    - if: unix
      then: bison
    - if: unix
      then: flex
    - if: unix
      then: gettext-tools
    - if: unix
      then: libiconv
    - if: unix
      then: libtool
    - if: unix
      then: gnuconfig
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - if: unix
      then: make
  run_exports:
    - ${{ pin_subpackage('libuuid') }}

tests:
  - script:
      - if: not win
        then: test -f ${PREFIX}/lib/libuuid.a
      - if: not win
        then: test -f ${PREFIX}/lib/libuuid${SHLIB_EXT}

about:
  license: BSD-3-Clause
  license_file: COPYING
  summary: Portable uuid C library.
  homepage: http://sourceforge.net/projects/libuuid/

extra:
  recipe-maintainers:
    - hmaarrfk
    - ocefpaf
