# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "j37SbiV8hnbUmwDWrQtMJQgrfmpwFpiT9XVRMehgt++Q3oJy0dVm2Mx4eJpGeUAkHy7CVcg2+XiruKs7N8zH+Rs+B83yTIfCBYJuMA7el0IvphLb7OzOH2vPH63c3DKC8T8lAjSzUy+kbD9fcfr7V5gwAudcnu9fQnoTqf5U0C+OeuaG1Wc2fQKuXnE/HwnU46AQQKpRDXh1sAK6ylHE5lHAreBUsrZ0abdbfZ6Iod7j03qWyBXm4tEBRJ2+NhDyOtZNh/NjLMysi4DYr08tElgifvGnFAbaLa7aVPgdpSxVg1EN3xswnHRRm4900Bpa1orvqR9ohR0+OjaNDeBBGzixE3SUpdsblV0h10++aS8dY0cdkGkgH+iahuv7y/b0LYescrDU1cr0q8ZOza4YwtwXTbbtmxJwB87rjHVedzqBJDmDGwv1xPPXUpJTVjOHlCDgKQlhfxND3HDSEtklQLAWnahmLTYOg235sFm871tr5bFEzXduFH8K0+QpymcQ9+Gxn6YTFYkl4J/ubDoC3NuZe5JPqGTIbg9LUmj072ojB8+0GMiysXn5SR+fy5xjt6bjFbQonrqy+fm58lDlXHQ1Rq5y2SoqgHMPVWdWBJspDSpRM1qte6nSzG///CSHDuZ6Gkur156rtAHtlcTqznAprBLpGFW6zR7jVC57x04="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
